"""
Generated by apps/marketing/scripts/generate-reference.mjs — do not edit.

Every Python snippet in the docs reference, checked against the real SDK. A renamed
method or a changed argument fails `mypy` rather than shipping a broken example.
Values are the OpenAPI document's own field examples, so both languages carry
identical data. Nothing here runs.
"""

from msgeasy import MsgEasy

client = MsgEasy("msg_test_key")


def verify_start() -> None:
    client.verify.start(
        phone="+919812345678",
        ttl_seconds=300,
        code_length=6,
    )


def verify_check() -> None:
    client.verify.check(
        verification_id="vrf_9f2c8d1e4b7a4c3f9e0d2a5b6c7d8e9f",
        code="483920",
    )


def media_upload() -> None:
    from pathlib import Path

    data = Path("invoice.pdf").read_bytes()
    client.media.upload(
        data,
        filename="invoice.pdf",
    )


def messages_send_text() -> None:
    client.messages.send(
        type="text",
        to="+919812345678",
        text="Your order has shipped.",
    )


def messages_send_template() -> None:
    client.messages.send(
        type="template",
        to="+919812345678",
        template_id="tpl_3b9f1c2d4e5a6b7c8d9e0f1a2b3c4d5e",
        variables={"1": "Asha", "2": "ORD-4471"},
    )


def messages_send_media() -> None:
    client.messages.send(
        type="media",
        to="+919812345678",
        media_id="med_7c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f",
    )


def messages_get() -> None:
    client.messages.get("msg_7726793e1a4b4c8d9e0f1a2b3c4d5e6f")


def templates_list() -> None:
    client.templates.list(
        limit=20,
        starting_after="tpl_3b9f1c2d4e5a6b7c8d9e0f1a2b3c4d5e",
    )


def templates_create() -> None:
    client.templates.create(
        name="order_shipped",
        category="UTILITY",
        language="en_US",
        body="Hi {{1}}, your order {{2}} has shipped.",
    )


def templates_get() -> None:
    client.templates.get("tpl_3b9f1c2d4e5a6b7c8d9e0f1a2b3c4d5e")


def templates_update() -> None:
    client.templates.update(
        "tpl_3b9f1c2d4e5a6b7c8d9e0f1a2b3c4d5e",
        name="order_shipped",
        language="en_US",
        body="Hi {{1}}, your order {{2}} has shipped.",
    )


def templates_validate() -> None:
    client.templates.validate(
        name="order_shipped",
        category="UTILITY",
        language="en_US",
        body="Hi {{1}}, your order {{2}} has shipped.",
    )
